spring:
log4j:
  logger:
    httpclient:
      wire: DEBUG

client:
  id: bs8kK-0DrHQ-vLfiZ4m_F-1h4RyYbVXBGvqdPbIvAlo=
  secret: 0MmHmxgmt4SMSFBvw_y0M90BeVbr1TUdhMWE3c6NM-A=
  redirectUri: http://localhost:4001/redirecting
  financialId: 0015800000jfwB4AAI
  state: ABC
  authorizationUsername: sukhramb
  authorizationAccount: 50000012345601
  tokenUrl: https://ob.rbs.useinfinite.io/token
  initRunning: true


tls:
  alias:
  enableMatls: false
  keyStore:
    location:
    password:
  trustStore:
    location:
    password:

aisp:
  target:
    context: /open-banking/v3.1/aisp
    baseUri: https://ob.rbs.useinfinite.io
    audience: https://api.rbs.useinfinite.io/authorize

pisp:
  target:
    context: /open-banking/v3.1/pisp
    baseUri: https://ob.rbs.useinfinite.io
    audience: https://api.rbs.useinfinite.io/authorize