spring:
log4j:
  logger:
    httpclient:
      wire: DEBUG

client:
  id: Iu9d7bXCe6pY-m6PQ1usvvzLj7OK8kHZBBv2XfLmvkM=
  secret: g-1HkcGC2U5hDnE3bReyCLEH-T3lbRsDfaXAF6FFJqE=
  redirectUri: http://localhost:4001/redirecting
  financialId: 0015800000jfwB4AAI
  state: ABC
  authorizationUsername: sukhramb
  authorizationAccount: 50000012345601
  tokenUrl: https://ob.rbs.useinfinite.io/token
  initRunning: true


tls:
  alias:
  enableMatls: false
  keyStore:
    location:
    password:
  trustStore:
    location:
    password:

aisp:
  target:
    context: /open-banking/v3.1/aisp
    baseUri: https://ob.rbs.useinfinite.io
    audience: https://api.rbs.useinfinite.io/authorize

pisp:
  target:
    context: /open-banking/v3.1/pisp
    baseUri: https://ob.rbs.useinfinite.io
    audience: https://api.rbs.useinfinite.io/authorize